from __future__ import annotations

import json
from pathlib import Path

from click import unstyle
from typer.testing import CliRunner

from ferryte.cli import app

runner = CliRunner()


def test_audit_bootstrap_writes_client_report(tmp_path: Path) -> None:
    out = tmp_path / "audit"

    result = runner.invoke(
        app,
        [
            "audit",
            "--client",
            "Acme <Test>",
            "--notes",
            "Internal & reviewed",
            "--answer",
            "The plan includes 24/7 support",
            "--answer-query",
            "What support is included?",
            "--out",
            str(out),
        ],
    )

    assert result.exit_code == 0, result.output
    assert "bootstrapped a self-contained" in result.output
    assert "InMemoryVectorStore (demo mode" in result.output
    assert (out / "audit.html").exists()
    assert (out / "audit.json").exists()

    payload = json.loads((out / "audit.json").read_text(encoding="utf-8"))
    assert payload["meta"]["client_name"] == "Acme <Test>"
    assert payload["meta"]["notes"] == "Internal & reviewed"
    assert len(payload["results"]) == 5

    rendered = (out / "audit.html").read_text(encoding="utf-8")
    assert "Acme &lt;Test&gt;" in rendered
    assert "5 Ferryte structural verification scenarios" in rendered
    assert "Generated by Ferryte" in rendered


def test_test_command_bootstrap_reaches_scenario_runner(tmp_path: Path) -> None:
    out = tmp_path / "reports"

    result = runner.invoke(app, ["test", "--report-dir", str(out)])

    # The deliberately leaky demo store may fail the gate, but bootstrap must
    # reach the scenario runner and produce the reports instead of exiting 2.
    assert result.exit_code in (0, 1), result.output
    assert "Report written" in result.output
    assert (out / "latest.html").exists()
    assert (out / "latest.json").exists()


def test_audit_rejects_unpaired_answer_query(tmp_path: Path) -> None:
    result = runner.invoke(
        app,
        ["audit", "--answer-query", "Question without an answer", "--out", str(tmp_path)],
        color=True,
    )

    assert result.exit_code == 2
    output = " ".join(unstyle(result.output).split())
    assert "--answer-query cannot be given more times than --answer" in output
